### ISSUE TITLE
이번달 기록에 대한 api 캐싱 부분 코드 변경

### ISSUE THREAD

**Issue by 42inshin** [innovationacademy-kr/24hane-frontend#55]
이번달인 경우, 기존 기록이 있고 없고의 유무에 따라서 api를 부를지 말지 결정하여 api 요청을 최소화하는 코드가 있었으나,
해당 코드로 인한 오류가 있어서 이번의 백엔드 api 속도가 전반적으로 빨라짐에 따라 해당 기능을 간소화하여 이번 달인 경우 perMonth api를 요청하도록 수정할 계획입니다.

**Comment by joohongpark** [comment]
고생하셨습니다 !
